version: '2'
services:
  sysman:
    image: centos-ssh:6.8
    hostname: sysman
    volumes:
      - ./sysman/home/setup/:/home/setup/:rw
      - ../:/home/setup/ansible:rw
      - ${HOME}/.ssh/:/home/setup/.ssh/:ro
      - ${HOME}/.dotfiles/:/home/setup/.dotfiles/:ro
      - ${HOME}/opt/:/home/setup/opt/:ro
      - ./common/opt/toolbox/:/opt/toolbox/:ro
  web01:
    image: centos-ssh:6.8
    hostname: web01
    depends_on:
      - sysman
  web02:
    image: centos-ssh:6.8
    hostname: web02
    depends_on:
      - sysman
  biz01:
    image: centos-ssh:6.8
    hostname: biz01
    depends_on:
      - sysman
  biz02:
    image: centos-ssh:6.8
    hostname: biz02
    depends_on:
      - sysman
  app01:
    image: centos-ssh:6.8
    hostname: app01
    depends_on:
      - sysman
  app02:
    image: centos-ssh:6.8
    hostname: app02
    depends_on:
      - sysman
